services:
  # Test Service
  test:
    build:
      context: .
      target: test
    environment:
      - MIX_ENV=test
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network
    volumes:
      - .:/app
      - /app/deps
      - /app/_build/test
    command: >
      sh -c "mix test"

  # PostgreSQL Database for Testing
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work_time_test
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker for Testing
  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"  # Different port to avoid conflicts
      - "15673:15672"
    volumes:
      - rabbitmq_test_data:/var/lib/rabbitmq
    networks:
      - test_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_test_data:
  rabbitmq_test_data:

networks:
  test_network:
    driver: bridge

